// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Aptos.Specs.Features._06_Advanced
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Fee Payer (Sponsored) Transactions")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("advanced")]
    [NUnit.Framework.CategoryAttribute("optional")]
    public partial class FeePayerSponsoredTransactionsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "advanced",
                "optional"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features/06-advanced", "Fee Payer (Sponsored) Transactions", "  As an SDK user\n  I want to create sponsored transactions\n  So that a third part" +
                "y can pay gas fees on behalf of users", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "fee-payer.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create fee payer transaction with sponsor")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task CreateFeePayerTransactionWithSponsor()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create fee payer transaction with sponsor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a sender account", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.AndAsync("a fee payer (sponsor) account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("a RawTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("I create a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("the transaction should have the fee payer designated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create fee payer transaction with secondary signers")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task CreateFeePayerTransactionWithSecondarySigners()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create fee payer transaction with secondary signers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("a sender account", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync("secondary signer accounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("a fee payer account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("a RawTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.WhenAsync("I create a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("it should include all signers plus fee payer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer address is preserved")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerAddressIsPreserved()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer address is preserved", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("fee payer address \"0xSPONSOR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("I build a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("fee_payer_address should be \"0xSPONSOR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer signing message differs from multi-agent")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerSigningMessageDiffersFromMulti_Agent()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer signing message differs from multi-agent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("the same RawTransaction and secondary signers", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("I generate multi-agent signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.AndAsync("I generate fee payer signing message with sponsor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.ThenAsync("the messages should be different", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer signing message includes fee payer address")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerSigningMessageIncludesFeePayerAddress()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer signing message includes fee payer address", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("a RawTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.AndAsync("a fee payer address", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("I generate the fee payer signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("it should include the raw transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("it should include secondary signer addresses", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("it should include the fee payer address", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer signing message uses correct domain")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerSigningMessageUsesCorrectDomain()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer signing message uses correct domain", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("I generate the fee payer signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("it should start with SHA3-256(\"APTOS::RawTransactionWithData\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All parties (including fee payer) sign the same message")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task AllPartiesIncludingFeePayerSignTheSameMessage()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All parties (including fee payer) sign the same message", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
    await testRunner.GivenAsync("a fee payer transaction with sender, secondary, and sponsor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("each party generates their signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("all messages should be identical", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign fee payer transaction")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task SignFeePayerTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sign fee payer transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
    await testRunner.GivenAsync("a RawTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.AndAsync("sender account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("fee payer account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.WhenAsync("I sign the fee payer transaction with both parties", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("I should get a SignedTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
    await testRunner.AndAsync("the authenticator should be FeePayer variant", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer authenticator structure")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerAuthenticatorStructure()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer authenticator structure", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
    await testRunner.GivenAsync("a signed fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
    await testRunner.WhenAsync("I inspect the authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("it should contain sender authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.AndAsync("it should contain secondary_signer_addresses (may be empty)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("it should contain secondary_signers (may be empty)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("it should contain fee_payer_address", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("it should contain fee_payer_signer authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer with no secondary signers")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerWithNoSecondarySigners()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer with no secondary signers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
    await testRunner.GivenAsync("a sender account", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
    await testRunner.AndAsync("a fee payer account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.AndAsync("no secondary signers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.WhenAsync("I sign the fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("secondary_signer_addresses should be empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 94
    await testRunner.AndAsync("secondary_signers should be empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.AndAsync("fee payer should be present", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer with mixed account types")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerWithMixedAccountTypes()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer with mixed account types", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 99
    await testRunner.GivenAsync("an Ed25519 sender", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 100
    await testRunner.AndAsync("a Secp256k1 fee payer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
    await testRunner.WhenAsync("I sign the fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
    await testRunner.ThenAsync("it should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 103
    await testRunner.AndAsync("both authenticators should be correct types", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sender initiates sponsored transaction")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task SenderInitiatesSponsoredTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sender initiates sponsored transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 110
    await testRunner.GivenAsync("a sender who wants sponsored transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
    await testRunner.WhenAsync("sender creates RawTransaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 112
    await testRunner.AndAsync("sender signs the fee payer signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
    await testRunner.ThenAsync("sender can send partially signed tx to sponsor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sponsor completes sponsored transaction")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task SponsorCompletesSponsoredTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sponsor completes sponsored transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
    await testRunner.GivenAsync("a partially signed fee payer transaction from sender", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 118
    await testRunner.WhenAsync("sponsor reviews the transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.AndAsync("sponsor signs the fee payer signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.AndAsync("sponsor combines signatures into authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.ThenAsync("the transaction is ready for submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Signatures can be collected in any order")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task SignaturesCanBeCollectedInAnyOrder()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Signatures can be collected in any order", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 124
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 125
    await testRunner.GivenAsync("a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 126
    await testRunner.WhenAsync("sponsor signs first", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 127
    await testRunner.AndAsync("sender signs second", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
    await testRunner.AndAsync("I combine correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
    await testRunner.ThenAsync("the fee payer transaction should be valid", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer pays gas regardless of sender gas fields")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerPaysGasRegardlessOfSenderGasFields()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer pays gas regardless of sender gas fields", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 135
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 136
    await testRunner.GivenAsync("sender creates transaction with max_gas_amount=100", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
    await testRunner.AndAsync("fee payer has sufficient balance", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.WhenAsync("transaction is submitted", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
    await testRunner.ThenAsync("fee payer\'s balance is deducted for gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 140
    await testRunner.AndAsync("sender\'s balance is not deducted for gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Transaction fails if fee payer has insufficient gas")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task TransactionFailsIfFeePayerHasInsufficientGas()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transaction fails if fee payer has insufficient gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
    await testRunner.GivenAsync("sender creates valid transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
    await testRunner.AndAsync("fee payer has zero balance", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
    await testRunner.WhenAsync("transaction is submitted", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
    await testRunner.ThenAsync("it should fail due to fee payer insufficient balance", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reject missing fee payer signature")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task RejectMissingFeePayerSignature()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject missing fee payer signature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 153
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 154
    await testRunner.GivenAsync("a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 155
    await testRunner.WhenAsync("sender signs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
    await testRunner.ButAsync("fee payer does not sign", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
#line 157
    await testRunner.AndAsync("I try to create the authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.ThenAsync("it should fail with missing fee payer error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reject missing sender signature")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task RejectMissingSenderSignature()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject missing sender signature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 161
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
    await testRunner.GivenAsync("a fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
    await testRunner.WhenAsync("fee payer signs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
    await testRunner.ButAsync("sender does not sign", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
#line 165
    await testRunner.AndAsync("I try to create the authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
    await testRunner.ThenAsync("it should fail with missing sender error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer address must match signature")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerAddressMustMatchSignature()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer address must match signature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 169
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 170
    await testRunner.GivenAsync("fee payer address A", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
    await testRunner.AndAsync("signature from account B", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
    await testRunner.WhenAsync("I submit the transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
    await testRunner.ThenAsync("on-chain validation should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize fee payer authenticator")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task SerializeFeePayerAuthenticator()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Serialize fee payer authenticator", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 179
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 180
    await testRunner.GivenAsync("a fee payer authenticator", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 181
    await testRunner.WhenAsync("I BCS serialize it", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 182
    await testRunner.ThenAsync("the variant indicator should be FeePayer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 183
    await testRunner.AndAsync("all components should be serialized in order", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fee payer transaction serialization is deterministic")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task FeePayerTransactionSerializationIsDeterministic()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fee payer transaction serialization is deterministic", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 186
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 187
    await testRunner.GivenAsync("the same fee payer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 188
    await testRunner.WhenAsync("I serialize it twice", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 189
    await testRunner.ThenAsync("both serializations should be identical", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Known fee payer signing message test vector")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task KnownFeePayerSigningMessageTestVector()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Known fee payer signing message test vector", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 195
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 196
    await testRunner.GivenAsync("a RawTransaction and fee payer address from test vectors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 197
    await testRunner.WhenAsync("I generate the signing message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 198
    await testRunner.ThenAsync("it should match the expected value from test vectors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Known fee payer transaction test vector")]
        [NUnit.Framework.CategoryAttribute("optional")]
        public async global::System.Threading.Tasks.Task KnownFeePayerTransactionTestVector()
        {
            string[] tagsOfScenario = new string[] {
                    "optional"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Known fee payer transaction test vector", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 201
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 202
    await testRunner.GivenAsync("a fee payer transaction from test vectors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 203
    await testRunner.WhenAsync("I serialize it", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 204
    await testRunner.ThenAsync("the bytes should match expected value from test vectors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
