// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Aptos.Specs.Features._05_Api_Clients
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Gas Estimation")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("api-clients")]
    [NUnit.Framework.CategoryAttribute("preferred")]
    public partial class GasEstimationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "api-clients",
                "preferred"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features/05-api-clients", "Gas Estimation", "  As an SDK user\n  I want to estimate gas costs for transactions\n  So that I can " +
                "set appropriate gas parameters", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "gas-estimation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get current gas price estimate")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task GetCurrentGasPriceEstimate()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get current gas price estimate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a connected Aptos client", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("I request gas price estimate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("I should receive gas_estimate", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("the value should be in octas per gas unit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gas estimate includes priority options")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task GasEstimateIncludesPriorityOptions()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gas estimate includes priority options", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("a connected Aptos client", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("I request gas price estimate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("I should receive gas_estimate (standard)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("optionally prioritized_gas_estimate (faster)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("optionally deprioritized_gas_estimate (slower/cheaper)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Prioritized gas is higher than standard")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task PrioritizedGasIsHigherThanStandard()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Prioritized gas is higher than standard", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("gas price estimates", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
    await testRunner.WhenAsync("I compare prioritized vs standard", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("prioritized should be >= standard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deprioritized gas is lower than standard")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task DeprioritizedGasIsLowerThanStandard()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deprioritized gas is lower than standard", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("gas price estimates", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.WhenAsync("I compare deprioritized vs standard", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("deprioritized should be <= standard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gas estimates are positive")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task GasEstimatesArePositive()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gas estimates are positive", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("gas price estimates", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.ThenAsync("all estimates should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Simulate transaction for gas usage")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task SimulateTransactionForGasUsage()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simulate transaction for gas usage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("a valid transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
    await testRunner.WhenAsync("I simulate the transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("I should receive gas_used", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
    await testRunner.AndAsync("gas_used represents actual consumption", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Use simulation for max_gas_amount")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task UseSimulationForMax_Gas_Amount()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Use simulation for max_gas_amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("a transaction simulation result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("I extract gas_used", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("I can use it to set max_gas_amount with buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Simulation gas vs actual gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task SimulationGasVsActualGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simulation gas vs actual gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
    await testRunner.GivenAsync("a simulated and executed transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("I compare gas values", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("actual gas should be similar to simulated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("actual should not exceed max_gas_amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Complex transaction uses more gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task ComplexTransactionUsesMoreGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complex transaction uses more gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
    await testRunner.GivenAsync("a simple transfer transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
    await testRunner.AndAsync("a complex smart contract call", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.WhenAsync("I simulate both", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the complex call should use more gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Default gas parameters")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task DefaultGasParameters()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Default gas parameters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
    await testRunner.GivenAsync("a transaction builder with defaults", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
    await testRunner.WhenAsync("I check default values", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("max_gas_amount should be reasonable (e.g., 200000)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("gas_unit_price should be reasonable (e.g., 100)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Override gas unit price")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task OverrideGasUnitPrice()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Override gas unit price", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
    await testRunner.GivenAsync("current gas estimate is 150", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.WhenAsync("I build a transaction with gas_unit_price 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("the transaction should use price 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Override max gas amount")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task OverrideMaxGasAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Override max gas amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 91
    await testRunner.GivenAsync("a transaction builder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
    await testRunner.WhenAsync("I set max_gas_amount to 500000", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("the transaction should have that limit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gas price affects transaction priority")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task GasPriceAffectsTransactionPriority()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gas price affects transaction priority", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 97
    await testRunner.GivenAsync("two transactions with different gas prices", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
    await testRunner.WhenAsync("both are submitted", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("higher gas price should be processed first (usually)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculate total gas cost")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task CalculateTotalGasCost()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate total gas cost", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 106
    await testRunner.GivenAsync("gas_used = 1000 units", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
    await testRunner.AndAsync("gas_unit_price = 100 octas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.WhenAsync("I calculate total cost", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
    await testRunner.ThenAsync("total should be 100000 octas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Estimate maximum cost")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task EstimateMaximumCost()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Estimate maximum cost", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
    await testRunner.GivenAsync("max_gas_amount = 200000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 114
    await testRunner.AndAsync("gas_unit_price = 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.WhenAsync("I calculate maximum possible cost", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
    await testRunner.ThenAsync("max cost should be 20000000 octas (0.2 APT)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Actual cost vs maximum")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task ActualCostVsMaximum()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Actual cost vs maximum", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
    await testRunner.GivenAsync("a completed transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
    await testRunner.WhenAsync("I compare actual cost to max possible", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
    await testRunner.ThenAsync("actual should be <= max possible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.AndAsync("difference is refunded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Transaction fails with insufficient max gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task TransactionFailsWithInsufficientMaxGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transaction fails with insufficient max gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 129
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 130
    await testRunner.GivenAsync("a transaction requiring 50000 gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 131
    await testRunner.WhenAsync("I submit with max_gas_amount = 10000", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
    await testRunner.ThenAsync("transaction should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 133
    await testRunner.AndAsync("error should indicate out of gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Account has insufficient balance for gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task AccountHasInsufficientBalanceForGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account has insufficient balance for gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 136
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 137
    await testRunner.GivenAsync("an account with 1000 octas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 138
    await testRunner.AndAsync("a transaction requiring 10000 octas gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.WhenAsync("I try to submit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
    await testRunner.ThenAsync("submission should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 141
    await testRunner.AndAsync("error should indicate insufficient balance", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Simulation catches insufficient gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task SimulationCatchesInsufficientGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simulation catches insufficient gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 145
    await testRunner.GivenAsync("a transaction with very low max_gas_amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 146
    await testRunner.WhenAsync("I simulate it", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
    await testRunner.ThenAsync("simulation should show failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 148
    await testRunner.AndAsync("should indicate gas exhaustion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Auto-estimate gas for transaction")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task Auto_EstimateGasForTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Auto-estimate gas for transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 154
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 155
    await testRunner.GivenAsync("an Aptos client with auto-gas enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 156
    await testRunner.WhenAsync("I submit a transaction without specifying gas", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 157
    await testRunner.ThenAsync("SDK should simulate first", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 158
    await testRunner.AndAsync("set appropriate max_gas_amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Apply buffer to gas estimate")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task ApplyBufferToGasEstimate()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Apply buffer to gas estimate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 161
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
    await testRunner.GivenAsync("simulated gas_used = 10000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
    await testRunner.WhenAsync("I apply 20% buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
    await testRunner.ThenAsync("max_gas_amount should be 12000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fetch current gas price before submission")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task FetchCurrentGasPriceBeforeSubmission()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fetch current gas price before submission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 167
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 168
    await testRunner.GivenAsync("an Aptos client", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 169
    await testRunner.WhenAsync("I build transaction without specifying gas_unit_price", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 170
    await testRunner.ThenAsync("SDK should fetch current estimate", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 171
    await testRunner.AndAsync("use it for the transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gas prices vary by network load")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task GasPricesVaryByNetworkLoad()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gas prices vary by network load", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 177
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 178
    await testRunner.GivenAsync("network is under high load", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 179
    await testRunner.WhenAsync("I check gas estimates", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 180
    await testRunner.ThenAsync("estimates should be higher than usual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Different networks have different gas")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task DifferentNetworksHaveDifferentGas()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Different networks have different gas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 183
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 184
    await testRunner.GivenAsync("mainnet and testnet clients", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 185
    await testRunner.WhenAsync("I check gas estimates on each", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 186
    await testRunner.ThenAsync("values may differ between networks", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Handle gas estimation failure")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task HandleGasEstimationFailure()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle gas estimation failure", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 192
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 193
    await testRunner.GivenAsync("a network error during estimation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 194
    await testRunner.WhenAsync("I request gas estimate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 195
    await testRunner.ThenAsync("I should receive an appropriate error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Handle invalid gas parameters")]
        [NUnit.Framework.CategoryAttribute("preferred")]
        public async global::System.Threading.Tasks.Task HandleInvalidGasParameters()
        {
            string[] tagsOfScenario = new string[] {
                    "preferred"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle invalid gas parameters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 198
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 199
    await testRunner.GivenAsync("gas_unit_price = 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 200
    await testRunner.WhenAsync("I try to submit transaction", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 201
    await testRunner.ThenAsync("it should fail with validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
